apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: saraaw/fastfood-app:latest
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://mysql:3306/fastfood"
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # livenessProbe: 
        #   exec:
        #     command: ["/usr/bin/mysql", "-uroot", "-prootpassword", "-e", "SHOW DATABASES"]
        #   initialDelaySeconds: 60
        #   periodSeconds: 10