version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: fastfood-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastfood
      MYSQL_TEST_DATABASE: fastfood_test
      MYSQL_USER: user-admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - local-network

  adminer:
    image: adminer
    container_name: fastfood-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - local-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - local-network
    depends_on:
      - mysql

networks:
  local-network:
    driver: bridge